api.url=http://localhost:4111
api.apiVersion=/api/v1/
admin.username=admin
admin.password=admin
selenide.remote=http://localhost:4444/wd/hub
selenide.url=http://nginx
selenide.browser=firefox
selenide.browserSize=1920x1080