services:
  backend:
    image: nobugsme/nbank:with_validation_fix
    ports:
      - "4111:4111"
    networks:
      - nbank-network

  frontend:
    image: nobugsme/nbank-ui:with_nginx_with_send_transfer_fix
    expose: # не открываем порт наружу, а даем доступ контейнерам в сети
      - "80"
#    ports:
#      - "3000:80"
    depends_on:
      - backend
    networks:
      - nbank-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - nbank-network

  selenoid:
    image: aerokube/selenoid:1.10.9

    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/:/etc/selenoid/:ro
    environment:
      DOCKER_API_VERSION: 1.52
    command: ["-container-network", "nbank-network"]
    depends_on:
      - frontend
    networks:
      - nbank-network

  selenoid-ui:
    image: aerokube/selenoid-ui:1.10.7
    ports:
      - "6567:8080"
    command: [
      "--selenoid-uri", "http://selenoid:4444",
      "--allowed-origin", "*",
      "--timeout", "10s",
      "--period", "2s"
    ]

#    command: [
#      "--webdriver-uri", "http://192.168.31.102:4444",  # ваш IP
#      "--status-uri", "http://selenoid:4444"
#    ]

    depends_on:
      - selenoid
    networks:
      - nbank-network

networks:
  nbank-network:
    name: nbank-network